/* Test to schedule and verify autogenerated hashtags for IG first comment */
const { test, expect} = require('@playwright/test');
const tearDown = require('../../../../custom-commands/tearDown');
const {ComposePage} = require('../../../../pages/planandcreate/compose');
const {getObjectByName} = require('../../../../globals');
const {LoginPage} = require('../../../../pages/login');
const getFixture = require('../../../../custom-commands/getFixture');
const { PlannerPage } = require('../../../../pages/planandcreate/planner');
let igbAccount, liAccount, memberId;

test.afterEach(async ({ page }) => {
	const cleanUp = new tearDown();

	await cleanUp.command();
	await page.close();
});


test('Schedule and edit hashtags for IG first comment', async ({ page }) => {
	const scheduleText = 'IG Comment with hashtags ' + Math.floor(Math.random() * 1000);
	const commentHashtags = ['#contentCreation', '#digitalMedia', '#automation', '#socialMedia'];
	const firstCommentText = 'Adding hashtags to first comment '.concat(commentHashtags.join(' '));
	const editedScheduledText = ' #messagePreview';
	const editedFirstCommentText = firstCommentText.concat(' #latestTrends');

	const addFixture = new getFixture();
	const loginPage = new LoginPage(page);
	const composePage = new ComposePage(page);
	const plannerPage = new PlannerPage(page);

	await test.step('Setup user & accounts', async () => {
		await addFixture.command('igfc_hashtags_schedule', 'pro_user_composer', true, 300);
		igbAccount = getObjectByName(global.fixture, 'igfc_hashtags_schedule').instagramBusiness.username;
		liAccount = getObjectByName(global.fixture, 'igfc_hashtags_schedule').linkedinProfile.username;
		memberId = global.member[0].memberId;
	});

	await test.step('Login as pro user', async () => {
		await loginPage.signIn('igfc_hashtags_schedule');
	});

	await test.step('Delete residual scheduled messages via API', async () => {
		await plannerPage.deleteScheduleMessagesViaAPI(memberId);
	});

	await test.step('Select compose button', async () => {
		await composePage.selectComposeButton();
	});

	await test.step('Select IGB account from social network picker', async () => {
		await composePage.profileDropDown.click();
		await expect(composePage.snContentItems).toBeVisible();
		await composePage.selectSocialProfile(liAccount);
		await composePage.selectSocialProfile(igbAccount);
		await composePage.postToWrapper.click();
		await expect(composePage.profileListItemTitle).not.toBeVisible();
		await expect(page.locator('.vk-ComposerModal .vk-LinkedInPreview')).toBeVisible({timeout: 5000});
		await expect(composePage.emptyInstagramPreview).toBeVisible();
	});

	await test.step('Upload media to the post', async () => {
		await composePage.uploadMediaFile('test_data/publisher/images');
		await expect(composePage.mediaOverLay).toBeVisible();
	});

	await test.step('Write a message and verify its preview', async () => {
		await composePage.writeMessage(scheduleText);
		await composePage.verifyInstagramPreview(scheduleText);
		await composePage.verifyLinkedInPreview(scheduleText);
	});

	await test.step('Verify first comment is present for Instagram', async () => {
		await expect(composePage.instagramTab).toBeVisible();
		await composePage.instagramTab.click();
		await expect(composePage.firstCommentHeader).toBeVisible();
	});

	await test.step('Add first comment with hashtags', async () => {
		await expect(composePage.firstCommentHeader).toBeVisible();
		await composePage.firstCommentTextArea.click();
		await composePage.firstCommentTextArea.type(firstCommentText);
	});

	await test.step('Verify first comment hashtags in preview', async () => {
		await composePage.verifyInstagramFirstCommentPreview(firstCommentText);
		await expect(composePage.instagramFirstCommentHashtagLink).toHaveCount(4); //Verify there are 4 hashtags in first comment preview
	});

	await test.step('Schedule the message', async () => {
		await composePage.schedule();
	});

	await test.step('Verify scheduled message in planner preview pane', async () => {
		await expect(composePage.feCallOuts).not.toBeVisible();
		await plannerPage.showPreviewPane(scheduleText, igbAccount);
		await plannerPage.verifyTextInPreviewPane(scheduleText);
	});

	await test.step('Verify first comment with hashtags in planner preview pane', async () => {
		await plannerPage.verifyFirstCommentInPreviewPane(firstCommentText);
	});

	await test.step('Edit scheduled message', async () => {
		await page.waitForTimeout(1500);
		await plannerPage.editFromPreviewPane();
	});

	await test.step('Verify the post in composer', async () => {
		await composePage.verifyInstagramPreview(scheduleText);
	});

	await test.step('Edit the first comment', async () => {
		await expect(composePage.firstCommentSubHeader).toBeVisible();
		await composePage.firstCommentTextArea.click();
		await composePage.firstCommentTextArea.fill(editedFirstCommentText);
	});

	await test.step('Edit the message', async () => {
		await composePage.messageArea.click();
		await composePage.writeMessage(editedScheduledText);
	});

	await test.step('Verify message preview now has hashtag', async () => {
		await composePage.verifyInstagramPreview(editedScheduledText);
		await expect(composePage.instagramHashtagLink).toHaveCount(1); //Verify there is only one hashtag in message preview
		await composePage.verifyInstagramHashtagPreview('messagePreview');
	});

	await test.step('Verify updated hashtags in first comment preview', async () => {
		await composePage.verifyInstagramFirstCommentPreview(editedFirstCommentText);
		await expect(composePage.instagramFirstCommentHashtagLink).toHaveCount(5);
	});

	await test.step('Save the edited message', async () => {
		await composePage.saveEditedMessage();
	});

	await test.step('Verify edited text & first comment in planner preview pane', async () => {
		await expect(composePage.feCallOuts).not.toBeVisible();
		await plannerPage.verifyTextInPreviewPane(scheduleText.concat(editedScheduledText));
		await plannerPage.verifyFirstCommentInPreviewPane(editedFirstCommentText);
	});

	await test.step('Delete the scheduled message', async () => {
		await plannerPage.deleteFromPreviewPane();
	});
});
