apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  tunnel:
    name: 'sauce-playwright-tunnel'
    owner: '$SAUCE_USERNAME'
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
  launchOrder: fail rate
playwright:
  version: package.json # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
  configFile: playwright.config.js # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
env:
  AWS_SDK_LOAD_CONFIG: 1
  AWS_SHARED_CREDENTIALS_FILE: ".aws-session.saucelabs.ini"
  AWS_CONFIG_FILE: ".aws-config.saucelabs.ini"
npm:
  dependencies:
    - hsdynamodb
    - hsapi
    - underscore
    - date-fns
    - date-fns-tz
    - events
suites:
  - name: "[Playwright] Composer Tests"
    platformName: "Windows 11"
    screenResolution: "1920x1080"
    testMatch: ['tests/composer/send_now.spec.js']
    params:
      browserName: "chromium"
      project: "chromium"
  - name: "[Playwright] Composer Tests Firefox"
    platformName: "Windows 11"
    screenResolution: "1920x1080"
    testMatch: ['tests/composer/send_now.spec.js']
    params:
      browserName: "firefox"
      project: "firefox"
  # - name: "[Playwright] Composer Tests Safari"
  #   platformName: "macOS 13"
  #   screenResolution: "1920x1440"
  #   testMatch: ['tests/composer/send_now.spec.js']
  #   params:
  #     browserName: "webkit"
  #     project: "webkit"
  # - name: "[Playwright] Chrome Tests"
  #   platformName: "Windows 11"
  #   screenResolution: "1920x1080"
  #   testMatch: ['tests/composer/.*.js']
  #   params:
  #     browserName: "chromium"
  #     project: "chromium"
  # - name: "[Playwright] Firefox Tests"
  #   platformName: "Windows 11"
  #   screenResolution: "1920x1080"
  #   testMatch: ['tests/composer/.*.js']
  #   params:
  #     browserName: "firefox"
  #     project: "firefox"
  # - name: "[Playwright] Safari Tests"
  #   platformName: "macOS 13"
  #   screenResolution: "1280x960"
  #   testMatch: [ 'tests/composer/.*.js' ]
  #   params:
  #     browserName: "webkit"
  #     project: "webkit"
  # - name: "[Playwright] Planner Tests"
  #   platformName: "Windows 11"
  #   screenResolution: "1920x1080"
  #   testMatch: ['tests/planner/.*.js']
  #   params:
  #     browserName: "chromium"
  #     project: "chromium"
#  - name: "[Playwright] Test API Calls" #This suite will be removed eventually
#    platformName: "Windows 11"
#    screenResolution: "1920x1080"
#    testMatch: ['tests/apiCalls/.*.js']
#    params:
#      browserName: "chromium"
#      project: "chromium"
#  - name: "Webkit Win"
#     platformName: "Windows 11"
#     screenResolution: "1440x900"
#     testMatch: ['.*.js']
#     params:
#       browserName: "webkit"
#       project: "webkit"

# Controls what artifacts to fetch when the suites have finished.
artifacts:
  cleanup: true
  download:
    when: always
    match:
      - console.log
      - 'sauce-test-report.json'
      - '*.png'
    directory: ./artifacts/
